### ISSUE TITLE
Null-valued expression

### ISSUE THREAD

**Issue by apeppels** [G4lB1t/Invoke-NoShell#1]
Hi, and thanks for the awesome tool!
@jbremer sent me to see how it fairs in Cuckoo, however I'm getting some errors on (practically) the same setup as described in the README. Maybe you recognize the error.

```PS C:\Users\me\tools\Invoke-NoShell> .\Invoke-NoShell.ps1
--snip--
Please insert a path with the payload you wish to embed: C:\Users\me\tools\Invoke-NoShell\reverse_shell.ps1
Please enter text to fool the victim that this is a legit doc: o hai thar doge
Please select manual or auto mode:
[A] - Auto mode, will generate all possible permutations
[M] - Manual mode, carefully select options to apply on a single document: A
You cannot call a method on a null-valued expression.
You cannot call a method on a null-valued expression.
You cannot call a method on a null-valued expression.
--snip--
PS C:\Users\me\tools\Invoke-NoShell> $error.InvocationInfo
--snip--
At C:\Users\me\tools\Invoke-NoShell\Invoke-NoShell.ps1:173 char:13
                        +             $doc = $word.documents.add()
```
Here, `$word` seems to be missing the `documents` field, even before the .doc is saved the first time.
Here are my specs:

```PS C:\> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  248

PS C:\> gwmi win32_operatingsystem | % caption
Microsoft Windows 10 Pro
PS C:\> $ENV:Processor_Architecture
AMD64
PS C:\> ls 'C:\Program Files (x86)\Microsoft Office\root\Office16\'

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        23-6-2018     15:44                1033
d-----        23-6-2018     15:44                1036
d-----        23-6-2018     15:44                3082
d-----        23-6-2018     15:44                AccessWeb
d-----        23-6-2018     15:44                ACCWIZ
d-----        23-6-2018     15:44                ADDINS
--snip--
```

On Office 2010 and 2013 it errors out on a different line:

```
You cannot call a method on a null-valued expression.
At C:\Users\me\tools\Invoke-NoShell.ps1:195 char:13
+             $Doc.VBProject.VBComponents("ThisDocument").CodeModule.Ad ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
Here it seems the `VBComponents("ThisDocument")` is lacking the `CodeModule` field. However this error happens after the document is saved and the path is printed.

Thanks in advance.

**Comment by G4LB1T** [comment]
When I execute similar input it looks like:
```
Please insert a path with the payload you wish to embed: c:\payloadz\danger.ps1
Please enter text to fool the victim that this is a legit doc: Hello Cuckoo world
Please select manual or auto mode:
[A] - Auto mode, will generate all possible permutations
[M] - Manual mode, carefully select options to apply on a single document: A
C:\Users\GalB.MVDEV\documents\MacroDocOutput\MacroDocTrueTrue0.doc
C:\Users\GalB.MVDEV\documents\MacroDocOutput\MacroDocTrueTrue1.doc
C:\Users\GalB.MVDEV\documents\MacroDocOutput\MacroDocTrueTrue2.doc
C:\Users\GalB.MVDEV\documents\MacroDocOutput\MacroDocTrueFalse0.doc
C:\Users\GalB.MVDEV\documents\MacroDocOutput\MacroDocTrueFalse1.doc
(...)
```

Getting:
```
You cannot call a method on a null-valued expression.
```
hints that something is very wrong here... if you debug the script, can you see where it gets the error?
I can't put my finger on any difference between our setups, it might be a thing I've overlooked or something else we are missing. I guess you double checked that there's a payload on:
```
C:\Users\me\tools\Invoke-NoShell\reverse_shell.ps1
```
I suggest to debug it with the free and quite awesome VisualStudio code to find the root cause.

**Comment by apeppels** [comment]
I'll dig in to the COM object basics you listed to get an idea of what I'm looking for, thanks. And yes, there's a powershell Meterpreter there. The script correctly errors out when the path is empty.

**Comment by G4LB1T** [comment]
Cool, I wonder why it happens - if you find anything broken feel free to open a pull request.

**Comment by apeppels** [comment]
It turned out to be this:
File->Options->Trust Center->Trust Center Settings->Trust access to the VBA object model

the following registry key did not get set for me for some reason.
HKCU\Software\Microsoft\Office\16.0\Word\Security\AccessVBOM

**Comment by G4LB1T** [comment]
Thanks @apeppels I actually have a function which should set this value from Invoke-NoShell itself, I wonder why it failed :(

**Comment by apeppels** [comment]
I see you've already tried to set it from the script. It looks like on my machine, the `TestRegistry*` functions don't work. 

When I step through here, (even when removing the `SilentlyContinue`) it always ends up returning true.

```
Try {
        Get-ItemProperty -Path $regkey -Name $name  -ErrorAction SilentlyContinue
        Return $true
    }
    Catch {Return $false}`
```
The same happend when running it outside of the debugger.
As an aside, a more reliable way to retrieve the office version might be 
`$officeVer = (New-Object -ComObject word.application).version`

I don't have the time to submit a PR, the issue is fixed for me now, but I hope this helps :)

**Comment by G4LB1T** [comment]
Thanks, much appreciated - I am working on a more reliable version of this function as we speak. If you are in Vegas the tool will be re-launched at BSidesLV, you will be a welcomed guest 🥇

**Comment by apeppels** [comment]
Thanks ever so much :)
